# Generated by Django 4.2 on 2024-08-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
    ]
